# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='average_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='average_experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='average_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
