# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_remove_metric_average_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='female_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='gender_diversity_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='male_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
